<?php
	return array(
		'model/entities/Page.php'=>'model/entities/Page.php',
		'model/containers/PageContainer.php'=>'model/containers/PageContainer.php',
		'modules/page/Action_page_add.php'=>'modules/page/Action_page_add.php',
		'modules/page/Action_page_delete.php'=>'modules/page/Action_page_delete.php',
		'modules/page/Action_page_display.php'=>'modules/page/Action_page_display.php',
		'modules/page/Action_page_displayAddForm.php'=>'modules/page/Action_page_displayAddForm.php',
		'modules/page/Action_page_displayDeleteForm.php'=>'modules/page/Action_page_displayDeleteForm.php',
		'modules/page/Action_page_displayEditForm.php'=>'modules/page/Action_page_displayEditForm.php',
		'modules/page/Action_page_edit.php'=>'modules/page/Action_page_edit.php',
		'modules/page/Action_page_index.php'=>'modules/page/Action_page_index.php',
		'templates/public/page/display.php'=>'templates/public/page/display.php',
		'templates/admin/page/add.php'=>'templates/admin/page/add.php',
		'templates/admin/page/display.php'=>'templates/admin/page/display.php',
		'templates/admin/page/displayAddForm.php'=>'templates/admin/page/displayAddForm.php',
		'templates/admin/page/displayDeleteForm.php'=>'templates/admin/page/displayDeleteForm.php',
		'templates/admin/page/displayEditForm.php'=>'templates/admin/page/displayEditForm.php',
		'templates/admin/page/edit.php'=>'templates/admin/page/edit.php',
		'templates/admin/page/index.php'=>'templates/admin/page/index.php'
	);
?>
